from Imagem import Imagem

lua1_gray = Imagem('../Imagens/Lua1_gray.jpg')
chessboard_inv = Imagem('../Imagens/chessboard_inv.png')
img02 = Imagem('../Imagens/img02.jpg')

lua1_gray.filtro_passa_baixa()
lua1_gray.sobel()
lua1_gray.magnitude_gradiente()
lua1_gray.direcao_gradiente()
lua1_gray.selecao_gradientes()
# print(lua1_gray.max_locais)
lua1_gray.bordas()
lua1_gray.salvar_imagem('../Testes/Sobel/Lua1_gray.png')

lua1_gray.prewitt()
lua1_gray.magnitude_gradiente()
lua1_gray.direcao_gradiente()
lua1_gray.selecao_gradientes()
lua1_gray.bordas()
lua1_gray.salvar_imagem('../Testes/Prewitt/Lua1_gray.png')

lua1_gray.scharr()
lua1_gray.magnitude_gradiente()
lua1_gray.direcao_gradiente()
lua1_gray.selecao_gradientes()
lua1_gray.bordas()
lua1_gray.salvar_imagem('../Testes/Scharr/Lua1_gray.png')

chessboard_inv.filtro_passa_baixa()
chessboard_inv.sobel()
chessboard_inv.magnitude_gradiente()
chessboard_inv.direcao_gradiente()
chessboard_inv.selecao_gradientes()
chessboard_inv.bordas()
chessboard_inv.salvar_imagem('../Testes/Sobel/chessboard_inv.png')

chessboard_inv.prewitt()
chessboard_inv.magnitude_gradiente()
chessboard_inv.direcao_gradiente()
chessboard_inv.selecao_gradientes()
chessboard_inv.bordas()
chessboard_inv.salvar_imagem('../Testes/Prewitt/chessboard_inv.png')

chessboard_inv.scharr()
chessboard_inv.magnitude_gradiente()
chessboard_inv.direcao_gradiente()
chessboard_inv.selecao_gradientes()
chessboard_inv.bordas()
chessboard_inv.salvar_imagem('../Testes/Scharr/chessboard_inv.png')

img02.filtro_passa_baixa()
img02.sobel()
img02.magnitude_gradiente()
img02.direcao_gradiente()
img02.selecao_gradientes()
img02.bordas()
img02.salvar_imagem('../Testes/Sobel/img02.png')

img02.prewitt()
img02.magnitude_gradiente()
img02.direcao_gradiente()
img02.selecao_gradientes()
img02.bordas()
img02.salvar_imagem('../Testes/Prewitt/img02.png')

img02.scharr()
img02.magnitude_gradiente()
img02.direcao_gradiente()
img02.selecao_gradientes()
img02.bordas()
img02.salvar_imagem('../Testes/Scharr/img02.png')